# -----------------------------
# Config file for *DIMet*
#Â Note: for indentation use space (never tab!): 2 space indents
# coments start with #
# -----------------------------

# -----------------------------
# necesary to all steps
# -----------------------------

metadata_path : ~/toy_metabologram/data/metadata_toy2.csv

name_abundance : rawAbundances
name_meanE_or_fracContrib : FracContribution_C
name_isotopologue_prop : CorrectedIsotopologues # isotopologue proportions
name_isotopologue_abs : null  # isotopologue absolute values (for toy_metabologram not avail)

conditions : 
 - Control # first must be control
 - L-Cycloserine 
 
suffix : cyc1
out_path : ~/toy_metabologram/analysis001/


# -----------------------------
# differential analysis
# -----------------------------
# # for two-clases comparison
grouping :  # see explanation at the  end
  - condition
  - timepoint  

comparisons :   # for each pair,last must be control
  - [L-Cycloserine_T0, Control_T0]         
              
statistical_test:
  abundances: prm-scipy  
  meanE_or_fracContrib: MW
  isotopologue_abs: null
  isotopologue_prop: MW
  

# thresholds     
thresholds:
  padj: 1
  absolute_log2FC: 0.3


# -----------------------------
# Plots
# -----------------------------
# metabolites to plot:
metabolites_to_plot:
  cell: ["Fructose_1,6-bisphosphate", # in "quotes" because has a comma inside
         L-Lactic_acid, Pyruvic_acid, L-Malic_acid,
         Fumaric_acid, L-Alanine, L-Glutamic_acid,
         L-Glutamine, L-Aspartic_acid]
  med:  [L-Lactic_acid, Pyruvic_acid, 
           L-Alanine, L-Asparagine]


# Abundances bars configuration
# -----------------------------
time_sel :
  - T0
  - T2h
barcolor : timepoint
axisx : condition
axisx_labeltilt : 20 # 0 is no tilt
width_each_subfig : 3
wspace_subfigs : 1

# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13


# -------------------- end of config file ---------------------         
# NOTE: Metabolograms need a separated configuration file
